# Use a base image
FROM alpine:latest

# Copy the bash script to the container
COPY refesh-cache.sh /refesh-cache.sh

# Set the working directory
WORKDIR /

# Make the script executable
RUN chmod +x /refesh-cache.sh
